spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yqlbd/test-config.git
          search-paths: cloud-simple
          username:
          password:
      label: master
server:
  port: 8780
